const FETCH_SMURFS_START = 'FETCH_SMURFS_START'
const FETCH_SMURFS_SUCCESS = 'FETCH_SMURFS_SUCCESS'
const FETCH_SMURFS_FAILURE = 'FETCH_SMURFS_FAILURE'


export { FETCH_SMURFS_START,FETCH_SMURFS_SUCCESS, FETCH_SMURFS_FAILURE}